name: Test Template
description: 테스트용 입니다. 사용하지 말아주세요.
title: "[Test] Title"
labels: ["feature"]

body:
  - type: markdown
    id: scrum-description
    attributes:
      value: |
        <details>
        <summary><h2>작업 상황 공유</h2></summary>
        <div markdown="1">

        #### 미뉴
        - [x] #2 
        - [x] #3

        </div>
        </details>

        <details>
        <summary><h2>오늘 할 일</h2></summary>
        <div markdown="1">

        #### 미뉴
        - [ ] #4 

        #### 에디
        - [ ] .

        #### 레인
        - [ ] .

        #### 하루
        - [ ] .

        #### 피칸파이
        - [ ] .

        </div>
        </details>

        <details>
        <summary><h2>ETC</h2></summary>
        <div markdown="1">

        #### 미뉴
        - 어쩌다보니 어제부터 작업이 시작되지 못했지만, 오늘부터 같이 으쌰으쌰 열심히 해봅시다! 화이팅~

        #### 에디
        - ㅇ

        #### 레인
        - ㅇ

        #### 하루
        - ㅇ

        #### 피칸파이
        - ㅇ


        </div>
        </details>
